#!/usr/bin/env python3


# red3
grocery     = [ "FARZIN'S NO FRI",
				"FORTINOS",
			    "FOOD BASICS",
			    "MY PROTEIN",
			    "NOFRILLS",
		      ]

# red3
resteraunts = [	"520 SUSHI",
				"7 ELEVEN",
				"ALI BABAS",
				"ALIMAS",
				"BASKIN ROBBINS",
				"BUBBLE TEA",
				"BURGER",
				"BURRITO",
				"CHOCOLATE",
				"DAIRY QUEEN",
				"EASTERN SENSE",
				"EATON RUBY THAI",
				"FIVE GUYS",
				"GATEWAY NEWSSTAND",
				"GATEWAY NEWSSTANDS",
				"GRILL",
				"GURU LUKSHMI",
				"HARVEYS",
				"KABOB",
				"KARAHI",
				"KERNELS POPCORN",
				"KFC",
				"KIMCHI KOREA HOUSE",
				"KOGANEI",
				"KWALITY",
				"LAZEEZ",
				"MANDI AFANDI",
				"MCDONALD'S",
				"MCDONALD",
				"METRO",
				"MIRCH MASALA",
				"MONTANAS",
				"OSMOW",
				"PIZZA",
				"POUTINERIE",
				"RAMYUN",
				"RESTAURANT",
				"RESTURANT",
				"SHAWARMA",
				"SKIPTHEDISHES",
				"SODA-SNACK",
				"SUBWAY",
				"THAI 5",
				"TIM HORTONS",
				"VILLAGE OF INDIA",
				"WING",
		  	   ]

# red3
entertain   = [ "BEER",
				"FAMOUS PLAYER",
				"LCBO",
				"MAZAJ",
				"ROLLERPLEX",
				"SHISHA",
				"SINDBAD",
		      ]

# orange
transport 	= [ "AIR-SERV",
				"CARS R US",
				"COSTCO",
				"ESSO",
				"HONKMOBILE",
				"HUDSON BAY",
				"IMPARK",
				"PARKING",
				"PETROCAN",
				"PRESTO",
				"SENECA",
				"SHELL",
				"UBER",
				"Uber",
		       ]

# orange
personal    = [ "AMAZON",
				"AMZN",
				"Amazon",
				"ASTRA",
				"Banggood.com",
				"BELL",
				"CDN TIRE",
				"DENTAL",
				"DOLLAR",
				"DOLLARAMA",
				"FIDO",
				"GOOGLE",
				"HARRY BEAUTY",
				"HOME DEPOT",
				"LOWES",
				"MOBIL330",
				"MUSEUM",
				"NATIONAL STUDENT LOANS",
				"OUACP",
				"PAYPAL",
				"PEOPLES JEWELLERS",
				"PET VALU",
				"PETSMART",
				"PLANET FITNESS",
				"ROGERS",
				"RYERSON",
				"SHOPPERS",
				"SHOPPER'S",
				"THE SOURCE",
		      ]

# orange
retail      = [ "DR MARTENS",
				"EMPIRE STREET",
				"H&M",
				"HUDSON'S",
				"OLD NAVY",
				"RW & CO",
				"SAKS OFF 5TH",
				"TIP TOP",
				"UNIQLO",
				"WAL-MART",

		      ]
# green2
credit      = [ "THANK YOU",
				"CashBack",
		      ]

# green2
pay         = [ "ATI TECHNOLOGIE",
			    "CASH BACK",
			    "MANULIFE",
			    "Branch Transaction INTEREST",
		      ]
# green2
savings     = [ "PREAUTHORIZED DEBIT CIBC-DISATF",
		      ]